- src/adapter.github.js
- src/octotree.js
> fix #150 #151

- src/adapter.github.js
It's related to #173 and #176.
> Fix detecting branch or tag name correctly

- src/adapters/adapter.js
- src/adapters/gitlab.js
- src/octotree.js
- src/styles/common.less
- src/view.options.js
the way I did with `adapter.setSidebar()` was silly. Still thinking about the better way.
> fix sidebar issues and style GL input

- src/adapters/github.less
original: https://github.com/buunguyen/octotree/blob/master/src/octotree.less#L29-L42
> Fix incorrect nesting level

- src/adapters/github.js
I add new selector to find the current branch and fix error when `match` an empty string.
> Add new selector for Github new design

- src/octotree.js
- src/template.html
> Should be compared with host and protocol both because `GHEURLS` stores protocol too

- src/adapters/adapter.js
- src/adapters/gitlab.js
Two improvements for a robust GitLab adapter.
> Fix GitLab URL for project/repository and file path

- src/adapters/adapter.js
- src/adapters/gitlab.js
Reverts buunguyen/octotree#233
> Revert "Fix GitLab URL for project/repository and file path"

- src/adapters/gitlab.js
> Add document width check to deal with GitLab CSS media query

- src/config/firefox/package.json
> Support private browsing mode on Firefox

- src/adapters/github.js
> Fix error when path is null

- src/adapters/gitlab.js
> Add RAW type to reserved names list

- README.md
Add gitlab repo that might help some users as we discussed at #280 and #282
> Add gitlab repo link

- src/adapters/gitlab.js
> Update Regex for new GitLab layout

- src/adapters/gitlab.less
It's fixed up #354 and following side effect.
> Fix the shifted side

- src/adapters/adapter.js
- src/view.tree.js
opens files, submodules and repositories in a new tab by clicking a link
while the ctrl button is pressed
this functions allows the user to serve multiple files simultaneously
and it provides the common feeling of an a-tag
> open files in a new tab if ctrl is pressed

- src/adapters/github.less
- src/adapters/octicons/file-directory.svg
updated with new github link color.
> updated with new github link color

- src/view.tree.js
This issue appeared during branch name is just number
> Fix script error

- README.md
Fix minor style issue and typo
Fix minor style issue and typo
> Fix minor style issue and typo

- gulpfile.babel.js
- src/config/safari/Info.plist
> Support file icons in Safari

- src/adapters/bitbucket.js
> Fix positions

- src/adapters/adapter.js
- src/main.js
- src/template.html
- src/view.error.js
- src/view.options.js
> Redirect user to Setting if their existing github token has problem

- src/adapters/github.js
> Update with Github HTML structure for branch selection

- src/main.js
> Fix mouse outside the sidebar not working in float mode

- src/styles/vars.less
Describe the problem.
Describe the solution.
Screenshots before and after applying the PR.
> Fix header height inaligned to Github header

- src/adapters/github.less
Describe the problem.
Describe the solution.
Screenshots before and after applying the PR.
> Fix blank space in error

- src/adapters/github.less
- src/styles/vars.less
- src/view.tree.js
> adjust content position based on header height

- src/adapters/github.less
> fix: header branch and repo ellipsis

- src/adapters/github.less
- src/core.constants.js
- src/main.js
- src/template.html
Address https://github.com/ovity/octotree/issues/648 and https://github.com/ovity/octotree/issues/651
> feat: add hover-to-show option as default

- src/adapters/github.less
> enhance: make resizable style more generic

- src/adapters/github.less
Fix https://github.com/ovity/octotree/issues/664
> Make sidebare appear faster

- src/main.js
Address:
https://github.com/ovity/octotree/issues/669
> fix: open the sidebar without interaction

- src/adapters/github.less
> enhance: reduce the closing lapse time

- src/template.html
> fix: add role in toggler for vimimum

- src/adapters/pjax.js
Github page refreshes when clicking a file on Octotree's sidebar
> Temporary fix: Github Code page refreshes when a file selected in sidebar

- src/main.js
Address https://github.com/ovity/octotree/issues/694
> fix: prevent closing the sidebar when clicking and not moving the mouse

- src/adapters/adapter.js
- src/adapters/github.js
Also address: 
- https://github.com/ovity/octotree/issues/691
- https://github.com/ovity/octotree/issues/682
> enhancement: reset dock before applying margin

- src/adapters/github.js
> fix: unpextected padding header when resizing sidebar

- src/adapters/github.js
> fix: pinned sidebar overlay the content in small screen

- src/adapters/github.js
Address https://github.com/ovity/octotree/issues/685
> enhancement: hide octotree in topics page

- src/adapters/adapter.js
- src/view.tree.js
> Refactor: add tree item interceptor

- src/adapters/github.less
- src/styles/vars.less
> Update css jstree anchor and octotree patch

- gulpfile.js
- src/main.js
- src/template.html
- src/view.ads.js
> feat: add octotree pro lines

- src/adapters/adapter.js
- src/adapters/github.js
- src/adapters/github.less
- src/view.tree.js
> truncate filename if it is overflow

- gulpfile.js
- src/adapters/adapter.js
- src/adapters/github.less
- src/util.plugins.js
- src/view.tree.js
> fix: truncate filename

- src/core.api.js
- src/main.js
> Add deactivate lifecycle in plugin

- src/adapters/github.js
- src/main.js
> fix: expand folders in pr page

- src/adapters/github.less
- src/styles/vars.less
- src/template.html
Describe the problem.
Fix for the heart font icon.
Describe the solution.
Screenshots before and after applying the PR.
> Fix font icon

- src/adapters/github.less
- src/template.html
> change layout of icons

- src/adapters/github.less
- src/template.html
> fix align of icons

- src/adapters/github.less
- src/template.html
spinner button is not in it's correct position this PR fixes it.
> Fix spinner icon position

- src/adapters/adapter.js
- src/adapters/github.js
> Replace PR #837

- src/adapters/github.js
> Revert "Fix layout on New PR page"

- src/adapters/github.js
> Revert "Fix layout when sidebar is pinned"

- src/adapters/github.less
> Change header border-right color

- src/adapters/github.js
> Revert "Revert "Fix layout on New PR page""

- src/adapters/adapter.js
> Revert "fix PR navigation"

- src/adapters/adapter.js
- src/adapters/github.js
- src/adapters/github.less
- src/core.constants.js
- src/main.js
- src/template.html
- src/view.tree.js
https://twitter.com/furixturi/status/1233228545125519360
#895 
Github has changed. The files navigation is broken, it no longer links to the correct files and works as we expected.
Fixing this would be too overhead and would add so much complexity to both code and usability. So the solution is to **remove this feature**.
> Remove PR changes view

- src/view.tree.js
Revert the download raw file feature removed by #903
> revert download raw feature

- src/adapters/adapter.js
fixes https://github.com/ovity/octotree/issues/912
> Change text in error forbidden tab

- src/adapters/adapter.js
- src/adapters/github.less
- src/styles/vars.less
- src/view.tree.js
> Revert "Replace raw file path on tree file to edit path"

- src/core.constants.js
- src/core.storage.js
fixes https://github.com/ovity/octotree/issues/919
> Refactor storage to support values per host

- src/core.storage.js
This is a follow up fix for #934
> Add check for unset storages values to #934

- src/adapters/github.js
> fix New PR page layout

- src/adapters/github.js
- src/main.js
Add the PR number into the repo details
> Add pull request number to repo details

- src/adapters/github.less
follow up https://github.com/ovity/octotree/pull/940
> Fix icons position on large screens

- src/adapters/github.js
Due to #890 , the page content is shift left and right on several pages before staying at its desired position
> Fix flickering layout

- src/core.storage.js
Migrate all storages except safari into storage.sync
> Migrate to storage.sync

- src/adapters/github.js
Sidebar overlap the notification bar, and page content when the browser is small or in some pages such as https://github.com/majodev/google-webfonts-helper/search?q=unicode&unscoped_q=unicode
> Fix update layout

- src/adapters/github.js
On small screen, sidebar overlap the page body
> Fix update layout on small screen
