test/specs.js
Root cause: the driver object from factory is returned (via callback) while the browser app hasn't been ready yet
Solution: wait for 5 seconds
=> Fix: page is still blank after browser launched

src/adapter.github.js
Hi, octotree is a great extension. When I started to work on my own GitHub extension ([GitHub Hovercard](https://github.com/Justineo/github-hovercard)), I learnt quite a lot from your code.
After digging around GitHub website, I found the reserved usernames should include more and sometimes we may ran into some non-reserved tokens that are not usernames (.eg `password_resest`). I used a regex to filter out invalid usernames in my own extension (`/^[a-z0-9]+$|^[a-z0-9](?:[a-z0-9](?!--)|-(?!-))*[a-z0-9]$/i`). Hope this helps.
=> add more reserved usernames

src/adapters/github.js
Octotree can't find a correct branch name in pull request page. Ex: https://github.com/defunkt/jquery-pjax/pull/597
I also see that Github expands one more `<link>` into `<head>` when you navigate to several pages. This  is also handled in this commit.
=> Fix finding a wrong branch in pull request page

.gitignore, src/adapters/gitlab.js
* After install from [Chrome Web Store](https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc/related), it display unfriendly on GitLab 7.5.3 b656b85
* Fixed it by adjusting margin-left of '.container>.content' and '.main-nav'
=> GitLab 7.5.3 b656b85: fix display unfriendly

src/adapters/adapter.js
When visiting repos which return `403 Forbidden`, for example: https://github.com/oh-my-fish/oh-my-fish
It shows `getCreateTokenUrl is not defined`
see the screenshot, in the second screenshot, octotree is empty.
=> fixed: function getCreateTokenUrl is not defined

src/octotree.js, src/view.help.js
This happens when octotree not able to access a repo(HTTP 403) example: https://github.com/oh-my-fish/oh-my-fish. But the 'empty' popup is not removed. which causes the link of `repo owner` and/or link to  the `repo` can not be reached.
See the screenshot below:
=> fixed: popup overlay not removed when there is error

src/adapters/github.js
It's used like username on GHE when [domain is http(s)://[hostname]/gist](https://help.github.com/enterprise/2.4/user/articles/creating-gists/#creating-a-gist)
=> Add reserved username

src/adapters/github.js, src/octotree.js
Extension is still working in Chrome for me.
I am having issues with running tests locally. Both in my branch and in `master`, I'm seeing the following failure in the `chrome init should toggle upon button click` test case:
```
1) chrome init should toggle upon button click:
AssertionError: false == true
at /Users/andrew/Documents/octotree/test/specs.js:58:16
at next (native)
at Domain.<anonymous> (/Users/andrew/Documents/octotree/node_modules/starx/lib/index.js:26:56)
at Domain.run (domain.js:228:14)
at next (/Users/andrew/Documents/octotree/node_modules/starx/lib/index.js:25:12)
at /Users/andrew/Documents/octotree/node_modules/starx/lib/index.js:140:10
at cb (/Users/andrew/Documents/octotree/node_modules/starx/lib/index.js:34:41)
at …
```
=> Attempt to fix #264

package.json
Test run after a fresh git clone + npm install fails attempting to run chromedriver.
```
Error: File does not exist: /Users/andrew/Documents/octotree/node_modules/chromedriver/lib/chromedriver/chromedriver
```
=> Add ChromeDriver as an explicit devDependency

src/adapters/adapter.js, src/view.tree.js
Fix middle click behaviors:
- Do not open links in the current tab. Fix #201.
- Directory links can be opened in new tab.
=> Fix middle click behaviors

src/adapters/gitlab.js
the used field for the repository id in gitlab (> v8.5.x) is search_project_id  not project_id
=> Support new project ID field in latest GitLab

src/adapters/github.js
=> Skip when a url ends with `.patch`, `.diff`

src/adapters/gitlab.js
It looks like this now:
https://gitlab.com/profile/personal_access_tokens
=> Update GitLab access token URL

src/adapters/github.js
Add a missing `||` operator which was deleted in https://github.com/buunguyen/octotree/commit/b349180b9099516932991eb60c86040a76f9dfa4?diff=unified#diff-7442ec7ebd4a6a56cbd510da52266f95R154
=> Add a missing OR operator

src/adapters/adapter.js
This PR resolves a typo displayed when private repos are connected to without an access token:
**Before:**
```Accessing private repositories requires a access token.```
**After:**
```Accessing private repositories requires an access token.```
=> Fixed typo.

src/adapters/github.js, src/styles/base.less, src/template.html
The call made to get the files for a specific pull request defaults to only 30 per response. Larger PR's can have more than that many files.
The max that can be returned is 300 (per https://developer.github.com/v3/pulls/#list-pull-requests-files), so raised the limit to that.
=> Raise pr-tree response limit to max (300)

src/view.tree.js
This PR fixes issue https://github.com/buunguyen/octotree/issues/434, where the combination of lazy loading and pull request view was causing recursive trees to appear.
To reproduce the issue, navigate to any PR and change your settings to:
`Load entire tree at once: false`
`Show only pull request changes: true`
To fix, we add logic to check if we are in Pull Request mode to `view.tree.js`
Here is the tree in the repo linked to in https://github.com/buunguyen/octotree/issues/434 with the fix:
=> Fix issue with lazy loading and PR view

src/config/chrome/background.js
bitbucket url should be added to whitelist because it is required permissions.
you can see the error in extension developer tools.
=> background: fix error while running permissions.remove

src/adapters/pjax.js
@buunguyen, when reviewing files on Github, each page click issues a pjax request for every file clicked on.  This seems unnecessary to me since all files are on the same page just with different anchors.  It would be better to just navigate to the requested anchor instead of refetching the page.
This modifies `pjax.selectFile` to skip the fetch if the request is for a different anchor on the same page that the user is already on
=> Skip pjax loads if requested path is for different anchor on same page

src/styles/base.less
Currently, the file icons are in italic.
This add the `font-style: normal` to the icons.
=> Fix file icons being in italic

src/adapters/github.js
Inspired by other github-related extensions (notably OctoLinker browser extension and OctoLinker) this PR aims to automate even more token generation providing the minimal preset of permissions.
**Before:**
https://github.com/settings/tokens/new
**After:**
https://github.com/settings/tokens/new?scopes=public_repo&description=OctoTree%20browser%20extension
=> Easier token generation on Github

src/adapters/bitbucket.js
Fixes #508. Bitbucket changed how where they render the `data-current-user` attribute. It has been moved from the `body` tag to its own `meta` tag directly inside the `<head>`. 
Here is what it looks like now:
Instead of selected the `data-current-user` from the `body`, grab it from the `meta` instead.
=> Get current user info from meta tag instead of body

src/styles/base.less
On small screens I always try to minimize the size of the octotree column. This PR aim to fix some edge-case behaviors.
| Summary of what issue(s) this PR resolves | Summary of what changes this PR proposes
| -- | -- |
| <img width="273" alt="schermata 2018-02-08 alle 00 02 57 2" src="https://user-images.githubusercontent.com/6209647/35982806-f71ff5b6-0cf0-11e8-855a-4027a5ff8e15.png"> | <img width="272" alt="schermata 2018-02-08 alle 00 06 28 2" src="https://user-images.githubusercontent.com/6209647/35982836-0b03d3b8-0cf1-11e8-90fa-ec37d9e418cb.png"> |
Tested on Firefox 58 and Chrome 64
=> Minor layout fixes

src/adapters/github.js
This addresses #473, where Octotree was not handling viewing the repo at commit level properly. In that case, it was not finding any branch or commit info, and falling back to `master`, and showing repo contents and links based on `master` instead of at the current commit.
This solution makes use of the fact that GitHub URL structure and API endpoints treat branches, labels, and sha commit references equivalently. The code now recognizes the commit sha from the URL and uses it as the branch. Therefore the sha is displayed in Octotree, used for the repo API call, and is present in all links generated.
This shows Octotree showing a repo at a commit:
=> Update GitHub repo parser to handle browsing repo at commit. Fixes #473.

src/adapters/github.js
Suggest another solution for the issue [#559](https://github.com/ovity/octotree/issues/559)
a @duylam , Could you check if I might miss any case ?
Many thanks.
=> Fix: get 404 when branch name has slash

src/adapters/github.js
For #602
If a branch is too long and contains an ellipsis `…` (three dots), then don't use that name as a branch name.
It falls back and tries other available methods.
=> Fix long branch names with ellipsis resulting in Error: Private repository

src/view.tree.js
Very often when I attempt to close or open a folder in the tree view, the following can happen:
- If the folder is closed, it will stay closed
- If the folder is opened, it will transition instantly to the close state and redo the opening animation 
- Usually it can be reproduced by clicking one folder, then clicking another different folder twice
By wrapping the close and open functions in a setTimeout, the issue disappears. It seems like the issue happens due to the functions getting called too early.
N/A
closes #613
=> Fix issue of folders opening or closing twice in a row

src/adapters/github.js
The branch name is not correctly parsed when it contains a `/`
When parsing the commits list, delete the initial `/username/reponame/commits/` instead of getting the last `/`.
You can check with this [PR branch](https://github.com/enizor/octotree/tree/enizor/fix-branch): the extension tried to use `fix-branch` instead of the whole `enizor/fix-branch` 
Maybe `currentRepo.username` should be used instead of only `username` (and similarly for `reponame`) but I did not understand when the two could differ
=> Fix(branch name guessing): handle `/` in branch name when using link

src/adapters/adapter.js, src/adapters/github.js, src/core.constants.js, src/octotree.js, src/view.tree.js
When it discovers that repo is too big to load it marks it and stores in the storage. Before each request it checks if the repo is huge. 
The first time it wants to fetch a huge repo it asks to refresh the page. This is "hack"-ish fix, since we need to retry loading lazily immediately. Could not find an elegant way to do this.
=> Mark huge repositories to load lazily later (#595)

src/main.js
Click file and mouse out doesn't automatically hide the sidebar in float mode. The reason is when loading a new file, `mouseenter` in the side is triggered after the file is loaded even the mouse is moved out the sidebar already.
Check if mouse is out the sidebar in the `mouseenter` event.
=> Prevent mouseenter triggered when mouse is out of the sidebar

src/main.js
Tracking `mouseleave` event to trigger the unpinned start timer is not always correct.
Actively tracking `mousemove` event in the document would be more natural.
=> Replace mouseleave with doc mousemove

src/adapters/github.less
Address https://github.com/ovity/octotree/issues/659
=> fix: hide the resizable sidebar completely

src/main.js
Address https://github.com/ovity/octotree/issues/663
=> fix: error shown when sidebar is closed in float mode

src/adapters/github.js
Fix https://github.com/ovity/octotree/issues/686
=> Fix: Github refreshes when the page is loaded at particular file

src/adapters/github.js
The URL path prefix "/users" is used for the new "sponsorship" feature of GitHub.
We don't need the sidebar on these pages.
Screenshots before and after applying the PR.
=> Enhancement: hide octotree on "users" page

src/adapters/github.js
Octo-tree shows up on marketplace pages.
Added `marketplace` to the `GH_RESERVED_USER_NAMES`
Before:
After:
(pending)
=> Add 'marketplace' to reserved usernames

src/adapters/github.less
https://github.com/ovity/octotree/issues/741
Modify CSS.
Before:
After:
=> Resolve issue #741 - tall letters are cut off

src/adapters/adapter.js
When path name is long, the current text is shown with "...".
Set 'title' for directory/file name so that full path is shown upon hover
=> add full path is shown upon hover

src/adapters/github.less
Tooltips in settings are hidden because of the overflow attribute
=> fix tooltip hidden

src/adapters/adapter.js, src/adapters/github.less, src/template.html
Disclaimer message for personal token usage in Octotree is not shown in settings view  
Adding a disclaimer message to make it clear token is stored in local storage.
=> Add disclaimer message for personal token usage.

src/main.js
This change is required for handling events in octotree pro feature (caching repo). For example once force reload is clicked the reload for both repo and cache should happen.
add boolean argument to EVENT.LOC_CHANGE to be passed into tryLoadRepo function.
=> Add reload argument to LOC_CHANGE event

src/adapters/github.js
This addresses issue #797, another set of URL's that are not repositories.
`customer-stories` is added to `GH_RESERVED_USER_NAMES`.
Note: Maybe `GH_RESERVED_USER_NAMES` should be alphabetized, for easier reference in the future? Happy to do this if desired.
=> Exclude customer-stories URL's from repository recognition.

src/adapters/github.js
* fixes #808 
Octotree appears on collection pages.
Visit any page under [Github Collections](https://github.com/collections), e.g:
* [Clean code linters](https://github.com/collections/clean-code-linters)
* [Open journalism](https://github.com/collections/open-journalism)
add `collections` to `GH_RESERVED_USER_NAMES`.
=> Add collections to GH_RESERVED_USER_NAMES

src/adapters/github.js
Some GitHub-themed Chrome extensions cause problems for Octotree because they reuse the branch-picker dropdown (specifically the `branch-select-menu` class) for other purposes, and Octotree's branch detection grabs an invalid value for the branch name, which cases the tree to fail to load.
This PR solves this problem in the releases and tags pages, by choosing `master` for the branch when at those url's. This works well because releases and tags are not per-branch git features anyway.
=> Default to master branch on releases and tags pages. Fixes #743.

src/adapters/github.less
The checkboxes in the setting screen are not well aligned with the label
Add vertical-align: middle;
Before
After
=> fix checkbox vertical alignment

src/adapters/github.less
Remove `overflow: hidden;` on octotree-setting-view
=> fix overflow issue in setting screen

src/main.js
On non-repo pages, the toggler appears for 1 sec then disappears
Hide the toggler by default, so that it does not need to wait for that 1 sec to get hidden
=> hide toggler by default

src/adapters/github.js, src/adapters/pjax.js
GitHub's own pjax implementation dispatches its events directly in the DOM, while the jQuery pjax library we use here dispatches its events only within its jQuery instance. 
Because some GitHub add-ons listen to certain pjax events in the DOM it may be necessary to forward an event from jQuery to the DOM to make sure those add-ons don't break. 
Fixes #490 
Dispatch the `pjax:start` and `pjax:end` events (for now) in the native DOM whenever they're dispatched within jQuery.
_Note that I don't forward the event details/extra parameters or whether they're cancellable at the moment, because the pjax implementations differ in this case and I could not find a case where this info is used by listeners._
Before this PR when navigating through Octotree:
After the PR or when navigating though …
=> Dispatch `pjax:end` event on native `document`

src/adapters/github.js, src/view.tree.js
Currently, in PR view, Octotree only shows the base branch as the branch name, and does not mention the head.
This PR detects the head branch (merge origin) name, and shows the branch name as "base < head", e.g. "master < new-shiny-feature".
Shown here in one of this repo's PR's:
=> Show pull request head with branch name. Fixes #542.

src/adapters/github.js
On create new PR page, octotree sidebar overlay the changed files section even when the sidebar is pinned
Change `adapter.updateLayout` behavior
Before
After
=> Fix layout on New PR page

src/adapters/github.js
When the octotree sidebar is pinned
- On create new PR page, it overlays the changed files section
- The page content got pushed to the right by 16px
Change `adapter.updateLayout` behavior, to:
- Always set margin-left for the whole page so that no elements will ever be overlayed
- Caculate the proper margin-left of the page's content to keep it at as near to its intial position as possible without pushing it to the right
Before
After
=> Fix layout when sidebar is pinned

src/main.js
This PR is to fix the recently merged #869 
Steps to produce:
Open 2 tabs, go to Settings in both tabs, change a setting in one tab and save -> the other tab is updated and shows the tree, but the Settings icon is still highlighted.
Force the toggler to remove it's active state when a different view is shown
=> fix optsView toggler state

src/core.storage.js
Syncing extStore among tabs does not work for object type data which are saved in localStorage
JSON.parse the values before notify the changes
=> Fix syncing local store

src/adapters/adapter.js
Can't navigate to files, GitHub probably has changed something
The best solution would be to change the href of the file in the tree to be same as the id of the diff in the page. But i couldn't find that hash string anywhere. 
So my approach is to select the diff in the page by its order.
=> fix PR navigation

src/adapters/adapter.js, src/adapters/github.less, src/styles/vars.less, src/view.tree.js
This PR is to replace the raw download path on the tree file into an edit path.
Few points i want to address before merging this : 
- Should we remove the lines from 279 till 294 in adapter.js ? as they are useless and are not used anywhere in codebase now https://github.com/ovity/octotree/blob/master/src/adapters/adapter.js#L279
- Current behavior is to navigate into the edit page without opening new tab, is that okay ? 
Screenshots on how the icon looks like when hovering over file path :
=> Replace raw file path on tree file to edit path

src/adapters/github.js
When there is multiple pjax cotainer on the page, the branchName become mastermaster or {branch}{branch}
=> Fix branchName

src/core.api.js
Octotree renders on Sponsors pages, which are not repos.
Add sponsors to list of reserved names.
Before:
I don't have an after screenshot because this is using Gulp 3, and I'm on Node 13: https://github.com/gulpjs/gulp/issues/2324 so I can't build and test.
=> fix: don't render on sponsors pages

src/adapters/github.less, src/styles/vars.less
When the screen width bigger than 1012px, height of header is wrong.
Add new variable and media query to solve the problem.
**Before**
**After**
=> fix: fix header height error at large layout

src/adapters/github.less, src/template.html
Fix https://github.com/ovity/octotree/issues/904
The last PR #906 was closed because that fix cause the tooltips to be cut off.
So the solution is having the tooltip display on the left side, no more overflow and being cut off
=> Fix scroll in settings view

src/adapters/github.less
fixes https://github.com/ovity/octotree/pull/932
After the mentioned PR some of the main header icons are not aligned probably this is a follow up PR to fix it.
Screenshots:
=> Minor UI changes

src/main.js
When API limit exceeded is shown sidebar won't toggle in :
- Issue page
- PR list page
Solution is by duplicating :
https://github.com/ovity/octotree/blob/master/src/main.js#L141 to https://github.com/ovity/octotree/blob/master/src/main.js#L142
inside the ```showError``` method
https://github.com/ovity/octotree/blob/master/src/main.js#L173
=> Fix sidebar toggling in error tabs

src/adapters/github.js
- go to https://github.com/notifications. Click any issue (also try pull request) in the big list in the center. Scroll -> notification bar disappear
- On PR page related to deleted branches, octotree crash
- notification bar disappear: set css explicity instead of overwriting all of elements's style which caused the loss of style position: sticky of notification bar
- Octotree crash: Unhandeled case when there is a deleted branche related to the PR
=> Fix noti disappear on PR page
